# Generated by Django 5.2.7 on 2025-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0002_order_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='realized_gain_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='realized_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='realized_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
