# Generated by Django 5.2.7 on 2025-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0003_remove_contact_updated_at_order_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='realized_gain_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
