# Generated by Django 5.2.6 on 2026-02-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0005_candle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('symbol', 'timeframe', 'time')},
        ),
    ]
