# Generated by Django 5.2.6 on 2026-02-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0006_alter_candle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
