# Generated by Django 5.2.6 on 2026-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0007_candle_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('signal', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('confidence', models.IntegerField()),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit_1', models.FloatField()),
                ('take_profit_2', models.FloatField()),
                ('take_profit_3', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
