# Generated by Django 5.2.6 on 2026-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseapp', '0008_signallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='signallog',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='direction',
            field=models.CharField(default='MULTI', max_length=20),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='entry_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='signal',
            field=models.CharField(default='MULTI_LAYER', max_length=50),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='stop_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='take_profit_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='take_profit_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='take_profit_3',
            field=models.FloatField(default=0),
        ),
    ]
